### ISSUE TITLE
PSR Log > 1

### ISSUE THREAD

**Issue by mattsah** [elazar/flystream#6]
Is there any intention to get a new major version here to support newer versions of the PSR Log interfaces?

**Comment by elazar** [comment]
@mattsah Good question! Thanks for filing this issue and for your interest in this library.

I'm admittedly not actively using it in any projects myself at the moment, so its maintenance has largely been on a reactive / as-needed basis.

That said, I agree that with PHP 7.4 being EOL and PHP 8.0 coming up on EOL within a month, "soon" would probably be a good time to release a new major version of this library that at least handles dependency version bumps, including `psr/log`.

I'll likely try to open up either an issue or a PR for this in the coming weeks, and would be happy to tag you closer to that time so that you can offer further feedback on related changes if you'd like. 😃

**Comment by elazar** [comment]
A few notable changes that I've added to the `master` branch thus far:
- Bumped minimum PHP version from 7.4 to 8.1 and `psr/log` from `^1` to `^2.0 || ^3.0` (see 4d84ad803e3f96f0966bca41efebcf24d4e6ecbf)
- Removed Pimple and replaced it with a custom PSR-11 container implementation, which did involve some BC-breaking changes to `ServiceLocator`, specifically removing some methods to access its internal container (see ac4592608da5efc76ad9351bf534286d2a3e01af)

@mattsah Are there any other major changes you'd like to see?
